API 모델 구현
DonggeonOh/bithumb-techcamp-ios-1st pull request #22
Opened 2022-02-25 07:56 UTC by HJEHA

- BaseURLable 프로토콜 생성 이유: API URL이 바뀔 수 있고, 테스트 URL 등 추가적인
  URL이 생길 경우 BaseURLable를 채택한 별도의 타입을 만들어 교체하면 되기 때문에
  확장에 용의하다
- Gettable extension으로 method 프로퍼티 기본구현: GET API별로 method 프로퍼티가
  중복되는걸 막을 수 있다

2022-02-25 08:16 UTC, z3rosmith approved these changes
좋은것같습니다!

2022-02-25 15:30 UTC, DonggeonOh requested changes
일단 API 관련 설계한 부분이 내일 코드리뷰를 통해서 다시 한번 이해 시켜주시면 좋을 것 같습니다.
이게 코드로만 보니까 어떤 의도로 작성하신건지 이해가 잘 안가네요 ㅠㅠ
그리고 컨벤션 관련한 부분만 고치면 좋을 것 같아요!

2022-02-25 15:30 UTC, DonggeonOh commented on BithumbYagomAcamedy/Model/BithumbPublicAPI/BithumbPublicAPI.swift
> +}
혹시 이 부분 관련해서 궁금 한 점이 있는데요.
Base URL을 바꾸는 경우가 있을까요? NetworkService에서 base URL을 갖고 있어서
처리하면 중복되는 부분이 사라질 것 같은데, 내일 중으로 API 관련해서 설계한 부분 설명 가능할까요?

2022-02-25 15:30 UTC, DonggeonOh commented on BithumbYagomAcamedy/Model/BithumbPublicAPI/GETMethod/GETMethods.swift
> +    {
혹시 컨벤션이
init 마지막이 ) { <- 이렇게 중괄호가 붙어야 하지 않나요?

2022-02-26 01:17 UTC, HJEHA commented on BithumbYagomAcamedy/Model/BithumbPublicAPI/BithumbPublicAPI.swift
> +}
테스트 서버를 따로 사용한다던지, 여러가지 이유로 Base URL이 바뀌는 경우는 종종 있을 것 같아서 다음과 같이 설계했습니다.
각 API 모델의 이니셜라이저를 통해 여러 BaseURL을 유연하게 사용할 수 있다고 판단하여 위와 같이 구현했습니다:)
회의실에서 따로 설명드리겠습니다:)

2022-02-26 01:31 UTC, z3rosmith approved these changes

2022-02-26 06:05 UTC, DonggeonOh approved these changes
구체적인 API 타입을 정의한 이유와 BaseURL 을 프로토콜로 정의한 부분이 궁금하네요 ㅎㅎ

2022-02-26 06:05 UTC, donggeonoh commented on BithumbYagomAcamedy/Model/BithumbPublicAPI/GETMethod/GETMethods.swift
> +}
API를 구체타입으로 하나하나 만들어놓으신 이유가 있을까요?
init에 orderCurrency 와 같은 파라미터를 딕셔너리로 관리하여 파라미터로 넘겨주는 것도 좋을 것 같은 생각이 들어서요.
정리하자면, 하나의 타입을 정의해서 각 api에 따라서 여러 개의 인스턴스를 만드는 것이 괜찮다는 의견인데 어떻게 생각하시나요?

2022-02-26 06:05 UTC, DonggeonOh commented on BithumbYagomAcamedy/Protocol/BaseURLable.swift
> +}
베이스 URL은 다 똑같은데 혹시 프로토콜로 분리한 이유가 있을까요?
구체 API 타입을 계속 유지한다고 하면, 하나의 BaseAPI를 만들어서 baseURL을 가지게 하면 될 것 같아서요!

2022-02-26 06:13 UTC, HJEHA commented on BithumbYagomAcamedy/Model/BithumbPublicAPI/GETMethod/GETMethods.swift
> +}
좋은 의견 감사합니다:)
저도 API 모델들을 구현하면서 공통적으로 사용되는 부분을 추상화 할 고민을 했었는데, 
API 모델별로 URL의 형태도 다르고, `Query Params`의 존재 여부 등을 고려했을 때
추상화를 진행하면 API 모델별로 명확함이 없어지는것 같아 API 모델을 각각의 구체 타입으로 구현했습니다.

2022-02-26 06:16 UTC, HJEHA commented on BithumbYagomAcamedy/Protocol/BaseURLable.swift
> +}
`BaseURLable` 프로토콜로 따로 만든 이유는 `개발용 URL`, `개발중인 서버 URL`등 baseURL을 쉽게 교체해 줄 수 있다고 판단하여 따로 만들었습니다.

2022-02-26 06:21 UTC, merged