코인 호가 화면 구현
DonggeonOh/bithumb-techcamp-ios-1st pull request #61
Opened 2022-03-07 02:09 UTC by HJEHA

### 구현 내용
  + 코인 상세 화면
    + 호가 컬렉션 뷰 구현
    + 호가 모아보기 구현
  + CoinOrderbookDataManager 구현
    + Orderbook HTTP 구현
    + Orderbookdepth 웹소켓 구현

### 구현 화면
![Simulator Screen Recording - iPhone 11 - 2022-03-07 at 10 58 00](https://user-images.githubusercontent.com/98801129/156955658-00eb269f-4765-48a9-9bf3-fcf85cab62bf.gif)

2022-03-07 06:48 UTC, z3rosmith commented on BithumbYagomAcamedy/View/CoinDetailView/CoinOrderbookView/CoinOrderbokDataManager.swift
> +            currentOrderbooks = resultOrderbooks.dropLast(resultOrderbooks.count - 30)
dropLast라는 메서드가 있네요 알아갑니다 👍👍

2022-03-07 06:50 UTC, DonggeonOh requested changes

2022-03-07 06:50 UTC, donggeonoh commented on BithumbYagomAcamedy/Model/Orderbook.swift
> +}
Transaction 타입에서도 쓰여서 String의 익스텐션으로 빼거나 protocol로 분리한 후 extension으로 구현해도 괜찮을 것 같습니다.

2022-03-07 06:50 UTC, donggeonoh commented on BithumbYagomAcamedy/Network/HTTP/Model/APIModels/OrderbookAPI.swift
> +        count: Int = 30,
API 상에서도 기본값이 30이네요. 👍👍👍
한 개만 필요한 곳에서 count를 지정해줘야겠네요.

2022-03-07 06:50 UTC, donggeonoh commented on BithumbYagomAcamedy/View/CoinDetailView/CoinOrderbookView/CoinOrderbokDataManager.swift
> +    func coinOrderbookDataManager(didChange askOrderbooks: [Orderbook], bidOrderbooks: [Orderbook])
func coinOrderbookDataManager(didChange askOrderbooks: [Orderbook], and bidOrderbooks: [Orderbook])
and 인자 라벨이 붙으면 더 좋을 것 같습니다!

2022-03-07 06:50 UTC, donggeonoh commented on BithumbYagomAcamedy/View/CoinDetailView/CoinOrderbookView/CoinOrderbokDataManager.swift
> +        let roundedQuantity = round(totalQuantity * digit) / digit
위의 roundedQuantity와 같이 protocol, extension을 통해 한 곳에서 처리할 수 있을거라고 생각해요 ㅎㅎ

2022-03-07 06:50 UTC, DonggeonOh commented on BithumbYagomAcamedy/View/CoinDetailView/CoinOrderbookView/CoinOrderbokDataManager.swift
> +        }
현재 orderbook 파라미터를 inout으로 받는 이유가 있을까요?
현재 orderbook에서 새로운 orderbook을 머지 한 후 현재 orderbook에 할당해주는 것은 어떻게 생각하시나요?

2022-03-07 06:50 UTC, DonggeonOh commented on BithumbYagomAcamedy/View/CoinDetailView/CoinOrderbookView/CoinOrderbokDataManager.swift
> +        }
아 혹시 ask, bid를 switch 문으로 처리하지 않고 inout으로 처리한게 맞을까요?

2022-03-07 06:50 UTC, DonggeonOh commented on BithumbYagomAcamedy/View/CoinDetailView/CoinOrderbookView/CoinOrderbokDataManager.swift
> +    }
혹시 WebSocketOrderBookDepthData 타입에서 ask, bid 각각을 들고있을 순 없는걸까요? 그렇게 하면 ask, bid를 필터링 하지 않아도 될 것 같아서요 ㅎㅎ

2022-03-07 06:50 UTC, DonggeonOh commented on BithumbYagomAcamedy/View/CoinDetailView/CoinOrderbookView/CoinOrderbookCollectionViewCell.swift
> +    }
기본 값으로 비어있을 것 같은데, String() 으로 초기화 해 준 이유가 궁금합니다.

2022-03-07 06:50 UTC, DonggeonOh commented on BithumbYagomAcamedy/View/CoinDetailView/CoinOrderbookView/CoinOrderbookViewController.swift
> +    private let coinOrderbookDataManager = CoinOrderbookDataManager()
바로 초기화해줘도 현재로선 상관 없지만, 개인적으로 추후 테스트 가능하게 하기위해
 viewDidLoad()에서 초기화 하는 것이 좋다고 생각이드네요 ㅎㅎ

2022-03-07 06:50 UTC, DonggeonOh commented on BithumbYagomAcamedy/View/CoinDetailView/CoinOrderbookView/CoinOrderbookViewController.swift
> +}
스크롤을 컬렉션 뷰 가운데에 위치하도록 수행하는 메서드인가요?
scrollToCollectionViewCenter()가 어떨까 싶네요 ㅎㅎ

2022-03-07 06:50 UTC, DonggeonOh commented on BithumbYagomAcamedy/View/CoinDetailView/CoinOrderbookView/CoinOrderbookViewController.swift
> +}
frame의 높이의 반을 빼준 이유가 가운데보다 반 정도 아래로 내려와서 frame의 반을 빼는거 맞나요?

2022-03-07 06:50 UTC, DonggeonOh commented on BithumbYagomAcamedy/View/CoinDetailView/CoinOrderbookView/CoinOrderbookViewController.swift
> +            }
데이터가 apply 되면 가운데로 스크롤 하려는 이유가 있을까요?

2022-03-07 06:50 UTC, DonggeonOh commented on BithumbYagomAcamedy/View/CoinDetailView/CoinOrderbookView/CoinOrderbookViewController.swift
> +        }
totalQuantity 오타 났습니다 ㅎㅎ

2022-03-07 07:02 UTC, z3rosmith commented on BithumbYagomAcamedy/View/CoinDetailView/CoinOrderbookView/CoinOrderbookViewController.swift
> +}
@DonggeonOh 화면(frame)의 정 중앙에 collectionView의 content를 맞춰주기 위해서인듯합니다

2022-03-07 07:55 UTC, HJEHA commented on BithumbYagomAcamedy/Model/Orderbook.swift
> +}
여러 곳에서 사용되는 기능이다보니 String Extension으로 빼도 좋겠네요:)
피드백 감사합니다

2022-03-07 07:57 UTC, HJEHA commented on BithumbYagomAcamedy/View/CoinDetailView/CoinOrderbookView/CoinOrderbokDataManager.swift
> +        }
호가 타입에 따라서 분기를 나누는 것보단 inout 매개변수을 사용하는게 조금 더 유연하게 사용할 수 있을 것 같아 inout 매개변수를 사용했습니다:)

2022-03-07 08:01 UTC, HJEHA commented on BithumbYagomAcamedy/View/CoinDetailView/CoinOrderbookView/CoinOrderbookCollectionViewCell.swift
> +    }
스토리보드의 priceLabel 등 "Label"이라는 기본값이 들어가 있어서 빈 문자열로 초기화 해줬습니다:)
스토리보드에서 기본값을 지워도 되지만 priceLabel 등 UI요소의 위치를 파악하기 힘들기 때문에 코드로 기본값을 넣어줬습니다:)

2022-03-07 08:04 UTC, HJEHA commented on BithumbYagomAcamedy/View/CoinDetailView/CoinOrderbookView/CoinOrderbookViewController.swift
> +    private let coinOrderbookDataManager = CoinOrderbookDataManager()
뷰컨을 테스트하기는 힘들 것 같습니다:)
DataManager를 옵셔널로 두고 viewDidLoad()에서 초기화 해주면 유연하게 DataManager를 교체할 수 있겠네요:)

2022-03-07 08:05 UTC, HJEHA commented on BithumbYagomAcamedy/View/CoinDetailView/CoinOrderbookView/CoinOrderbookViewController.swift
> +}
네이밍 피드백 감사합니다:)
동근, 제로가 예상하신대로 가운데 위치시키기 위해서 `frame의 높이 / 2`를 빼준게 맞습니다:)

2022-03-07 08:07 UTC, HJEHA commented on BithumbYagomAcamedy/View/CoinDetailView/CoinOrderbookView/CoinOrderbookViewController.swift
> +            }
데이터 초기 설정시 bidOrderbooks, askOrderbooks가 따로 넘어오기 때문에 apply의 컴플리션에 조건을 달아 컬렉션 뷰의 초기 위치를 설정하기 위함입니다:)

2022-03-07 08:16 UTC, HJEHA commented on BithumbYagomAcamedy/View/CoinDetailView/CoinOrderbookView/CoinOrderbokDataManager.swift
> +    }
WebSocketOrderBookDepthData의 연산 프로퍼티를 사용해서 개선할 수 있겠네요:)
피드백 감사합니다:)

2022-03-08 01:59 UTC, DonggeonOh approved these changes

2022-03-08 02:13 UTC, z3rosmith approved these changes

2022-03-08 02:59 UTC, merged